const useCaseWords = {
shopping: ["buy", "shop", "sale", "deal", "market", "retail", "store", "commerce", "purchase", "checkout",
  "cart", "coupon", "voucher", "promo", "discount", "offer", "order", "shipping", "delivery", "stock",
  "item", "product", "barcode", "price", "cost", "refund", "return", "wishlist", "bundle", "brand",
  "loyalty", "cashback", "carton", "basket", "payment", "billing", "credit", "card", "paypal", "upi",
  "cod", "pickup", "dropoff", "cartage", "shipment", "warehouse", "inventory", "list", "listicle",
  "supplier", "vendor", "merchant", "reseller", "boutique", "emporium", "hypermarket", "supermarket",
  "outlet", "mall", "bazaar", "plaza", "marketplace", "showroom", "stand", "stall", "kiosk", "booth",
  "storefront", "shoppe", "shoppes", "malling", "retailer", "seller", "buyer", "trader", "wholesaler",
  "distributor", "partnership", "trading", "transaction", "dealings", "purchasing", "procuring",
  "acquiring", "obtaining", "securing", "placing", "scanning", "tracking", "labeling", "filtering",
  "merchandising", "packaging", "loader", "logistics", "dispatch", "consignment", "processing",
  "handling", "fulfillment", "supply", "stockpile", "replenish", "reorder", "digital", "ecommerce",
  "online", "telemarket", "catalog", "catalogue", "click", "download", "e-tail", "webshop", "e-store",
  "app", "clickshop", "portal", "flea", "auction", "flash", "bargain", "clearance", "liquidation",
  "markdown", "rebate", "markup", "commission", "profit", "margin", "fee", "tax", "tariff", "spread",
  "register", "POS", "cashier", "till", "scanner", "terminal", "receipt", "invoice", "warranty",
  "exchange", "warranty", "guarantee", "cover", "insurance", "backorder", "preorder", "gift", "wrap",
  "wrapping", "treat", "present", "surprise", "vip", "premium", "elite", "plus", "max", "ultra",
  "eco", "green", "organic", "fairtrade", "handmade", "craft", "designer", "exclusive", "luxury",
  "budget", "cheap", "economy", "value", "doze", "bulk", "unit", "giftcard", "installments", "monthly",
  "subscribe", "subscription", "membership", "reward", "points", "redeem", "e-gift", "prepaid", "giftwrap",
  "firstorder", "bonus", "freebie", "bago", "tap", "fx", "intl", "dutyfree", "taxfree", "bogo",
  "referral", "invite", "invitefriends", "wishlist", "feedback", "compare", "filters", "ranking",
  "preview", "gallery", "demo", "fabric", "trackorder", "dispatch", "courier", "shippedon", "arrivingon",
  "support", "query", "chatbot", "livechat", "resolve", "policy", "survey", "free", "newarrival", "quickview"],


job:["about", "achievement", "administrator", "advisor", "agent", "analyst", "api", "applicant", "application", "apply",
  "appointment", "approval", "assessment", "assignment", "assistant", "associate", "ats", "attendance", "attitude", "authorization",
  "availability", "aws", "azure", "backend", "background", "basic", "behance", "benefits", "bio", "bonus",
  "bootcamp", "boss", "brief", "budget", "calendar", "call", "campus", "candidate", "canva", "career",
  "careerfair", "careergoals", "careerpath", "careerportal", "certificate", "certification", "check", "checking", "clock", "cloud",
  "coding", "collaboration", "college", "communication", "compliance", "conference", "confidence", "confirmation", "consultancy", "consultant",
  "contract", "contractor", "contracttype", "coordinator", "corevalues", "course", "coverletter", "creativity", "credential", "css",
  "ctc", "cv", "dashboard", "data", "database", "day", "deadline", "degree", "designer", "developer",
  "development", "director", "discipline", "doc", "document", "documents", "docx", "domain", "dribbble", "editor",
  "email", "employee", "employer", "employment", "engagement", "engineer", "ethics", "evaluation", "evaluator", "event",
  "excel", "executive", "exit", "experience", "expertise", "feedback", "figma", "fluent", "framework", "freelance",
  "freelancer", "frontend", "fullstack", "github", "gitlab", "glassdoor", "gmail", "goal", "goals", "google",
  "graduate", "growth", "hardware", "headhunter", "hire", "hiring", "hiringdrive", "hr", "hrms", "html",
  "identity", "indeed", "industry", "initiative", "innovation", "insurance", "intern", "internrole", "internship", "interview",
  "interviewee", "interviewer", "java", "javascript", "jira", "job", "jobboard", "jobhunt", "jobsearch", "jobsheet",
  "jobtitle", "jobtype", "joining", "joiningbonus", "journey", "kpi", "languages", "leader", "leadership", "learning",
  "linkedin", "links", "manager", "meet", "meeting", "mentorship", "mindset", "mission", "monster", "motivation",
  "native", "negotiation", "networking", "niche", "night", "notice", "noticeperiod", "notion", "objective", "offer",
  "offerletter", "office", "onboarding", "opening", "openings", "operator", "opportunity", "outlook", "ownership", "package",
  "passion", "payscale", "pdf", "performance", "permanent", "placement", "planning", "portfolio", "position", "posting",
  "ppt", "presentation", "probation", "productivity", "proficient", "programming", "project", "promotion", "proposal", "python",
  "qualification", "raise", "rating", "recruiter", "recruitment", "recruitmentfirm", "references", "referral", "referralprogram", "relocation",
  "remote", "renewal", "report", "resignation", "results", "resume", "review", "reviewer", "reward", "role",
  "rotational", "salary", "schedule", "screening", "selection", "selfemployed", "seminar", "separation", "sheet", "shift",
  "skills", "skillset", "slack", "slides", "slot", "software", "specialist", "spoken", "sql", "staff",
  "statement", "stipend", "strategist", "strategy", "strength", "summary", "supervisor", "support", "system", "talent",
  "target", "task", "tasks", "team", "teamwork", "tech", "technician", "technology", "telework", "termination",
  "time", "timing", "tools", "tracker", "train", "trainer", "training", "trainingperiod", "transcriber", "translator",
  "university", "vacancies", "vacancy", "vacancyid", "verbal", "virtual", "vision", "walkin", "weakness", "web",
  "webinar", "word", "work", "workflow", "workplace", "workshop", "writer", "written", "xlsx", "zoom"],


subscription: ["newsletter", "updates", "daily", "weekly", "monthly", "magazine", "digest", "news", "alert",
  "offers", "deals", "coupons", "promo", "promoalert", "discount", "flyer", "notify", "feed",
  "subscriptions", "content", "subscribe", "channel", "watch", "stream", "subscriptionbox",
  "mailinglist", "ebook", "guide", "resource", "courses", "class", "learning", "tutorials",
  "series", "tip", "tips", "insight", "trend", "buzz", "press", "feedreader", "autonews", "finance",
  "invest", "market", "crypto", "stocks", "mutualfund", "trading", "stockalert", "cryptoupdate",
  "investtips", "saas", "software", "crm", "productivity", "analytics", "app", "tool", "cloud",
  "webapp", "monitoring", "uptime", "tracking", "metrics", "status", "webhook", "notifier",
  "reminder", "calendar", "event", "planner", "note", "todo", "task", "focus", "habit", "wellness",
  "health", "fit", "workout", "run", "steps", "yoga", "meditate", "breathe", "selfcare", "lifestyle",
  "lifehack", "goals", "motivation", "mindset", "coach", "training", "mentor", "newsletterpro",
  "grow", "blog", "blogger", "technews", "startup", "vc", "founder", "bootstrap", "launch",
  "foundersletter", "growth", "hustle", "trendletter", "curated", "curation", "collections", "thread",
  "threads", "stack", "devnews", "coders", "frontend", "backend", "fullstack", "aiupdate", "genai",
  "openai", "chatgpt", "newslettergpt", "apicorner", "devdigest", "geekletter", "linuxnews",
  "cloudweekly", "cybersec", "privacy", "infosec", "vpnupdates", "techweekly", "uxnews", "uxui",
  "figma", "designfeed", "designdigest", "uiux", "photoshop", "illustrator", "branding", "product",
  "producthunt", "toolsweekly", "resourcemail", "freebies", "freestuff", "freemium", "premiumonly",
  "offeralert", "giftalert", "loot", "shoppingnews", "cashbacknews", "dealhunters", "dealnews",
  "emaildigest", "smartnewsletter", "quickread", "instaread", "readlater", "substack", "beehiiv",
  "ghost", "mailchimp", "convertkit", "moosend", "aweber", "sendy", "getresponse", "emailoctopus",
  "klaviyo", "campaignmonitor", "zapiernews", "notionweekly", "notionnews", "googlenews", "metaalert",
  "instagramtips", "reelupdate", "youtubenews", "creatorhub", "newslettergen", "emailfeed",
  "dailyfeed", "appnews", "betaupdate", "earlyaccess", "techfeed", "streamingnews", "netflixalert",
  "primeupdate", "huluweekly", "disneyupdate", "spotifynews", "soundcloud", "applepodcast", "rssfeed",
  "mailstream", "emailloop", "subfeed", "mailupdate", "dailybrief", "eveningupdate", "insidernews",
  "explorer", "subnote", "subbuzz", "mailflood", "infodrop", "newinfo", "productupdates", "features",
  "newsletterblast", "coursealert", "emaildrops", "pushnews", "techdrop", "inboxgem", "inboxjoy",
  "inboxbuzz", "inboxguru", "subscriptionguru", "learningpath", "traininghub", "mailhub", "mailscoop",
  "learnupdate", "studymail", "learningloop", "dailylessons", "newskill", "futuremail", "trendify",
  "earlybird", "waitlist", "alphamail", "betauser", "usertesting", "feedbackloop", "surveyupdates",
  "pollupdate", "trendalert", "earlynewsletter", "exclusiveletter", "alphaalert", "betanews",
  "freemiumalert", "premiumweekly", "insiderletter", "patreonmail", "kofiupdates", "fundingalert",
  "paidnewsletter", "courseupdate", "productrelease", "changelog", "devupdate", "patchnotes",
  "featurelist", "releaseupdate", "mondaymail", "fridaydrop", "weekendbrief", "midweekupdate",
  "morningbrief", "nightdigest", "workmail", "careerupdate", "newsbites", "quickmail", "digesthub",
  "dailybytes", "weekinreview", "weeklypicks", "contentdrop", "topcontent", "newsradar", "trendingnow",
  "hotnews", "mailblast", "inboxfire", "exploremail", "submailbox", "inboxbox", "smartfeed",
  "newsfusion", "freshdrop", "curatednews", "smartbrief", "fastupdate", "updatezone", "subscribehub", "alerts", "signup"],


freelancing: ["freelancer", "freelance", "remotejob", "remote", "remotehustle", "gig", "microgig", "sidejob",
  "sidehustle", "task", "assignment", "contractor", "consultant", "consulting", "project", "tasker",
  "jobportal", "jobsite", "jobboard", "onlinework", "jobhunt", "jobapply", "applynow", "nowhiring",
  "hired", "recruit", "recruiter", "hustler", "creativegig", "paidjob", "cashjob", "instantwork",
  "quickjob", "hourlygig", "perproject", "taskboard", "freelancejob", "freelancehub", "talenthub",
  "upwork", "fiverr", "freelancercom", "peopleperhour", "guru", "toptal", "hubstaff", "workana",
  "truelancer", "99designs", "designcrowd", "gigster", "weworkremotely", "remoteok", "flexjobs",
  "solidgigs", "indeedremote", "linkedinremote", "problogger", "freelancewriting", "dribbblejobs",
  "remotive", "workmarket", "remoteworkers", "codementor", "designjobs", "angeljobs", "startupjobs",
  "himalayas", "workingnomads", "jobspresso", "remotejobs", "remoteengineer", "techgig", "taskrabbit",
  "skillshare", "teachable", "upskills", "skillhunt", "gigboard", "jobboard", "tasklist", "hireme",
  "iamavailable", "openforwork", "hiredev", "hiredesigner", "hirewriter", "hiremarketer", "devforhire",
  "writerforhire", "creativeforhire", "opencontract", "contractready", "portfolio", "myportfolio",
  "viewportfolio", "seeprojects", "projectlist", "hirenow", "jobmatch", "matchjob", "jobconnect",
  "clientconnect", "gighunt", "clienthunt", "projecthunt", "proposal", "sendproposal", "submitbid",
  "jobbid", "jobquote", "proposalready", "coverletter", "cvattached", "resumelink", "mycv", "myresume",
  "jobready", "freelancecareer", "selfemployed", "fulltimefreelance", "onetimejob", "occasionalwork",
  "remoteincome", "makemoney", "earnonline", "earninggig", "incomestream", "freelancepay", "paypaljob",
  "paypertask", "weeklypay", "contractpay", "payinbtc", "payinvoice", "quickinvoice", "paymentdue",
  "taskdone", "jobdone", "milestonedone", "submitwork", "deliverable", "projectdelivery", "projectdone",
  "clientreview", "clientfeedback", "ratingupdate", "rateus", "freelancereview", "gigreview", "taskscore",
  "jobfeedback", "freelanceprogress", "milestoneready", "finalrevision", "revisiondone", "hiringupdate",
  "availability", "calendarlink", "booktime", "meetingrequest", "zoomlink", "freelancecall", "introcall",
  "kickoffmeeting", "checkinmeeting", "handoff", "handover", "finalhandover", "projectfiles",
  "projectassets", "projectfolder", "clientfolder", "drivefolder", "filelink", "downloadassets",
  "downloadproject", "docsattached", "figmalink", "notiondoc", "freelancenotes", "projectnote",
  "devlink", "githubrepo", "githublink", "previewlink", "testlink", "clientlogin", "adminpanel",
  "cmsaccess", "accessgranted", "tempaccess", "reviewaccess", "deliverylink", "demo", "livepreview",
  "demoaccess", "appdemo", "websitepreview", "uipreview", "designpreview", "freelancedesign",
  "freelancedev", "devgig", "devtask", "figmadesign", "adobedesign", "psddesign", "webproject",
  "mobileappjob", "androidgig", "iosjob", "websitejob", "landingpage", "ecommercegig", "wordpressgig",
  "elementorjob", "shopifyfreelance", "dropshippingdev", "customsite", "bugfixing", "devhelp",
  "webfix", "codinghelp", "techsupport", "virtualhelp", "onlineassistant", "va", "adminsupport",
  "dataentryjob", "spreadsheettask", "formjob", "excelgig", "automationtask", "macrojob", "aiwork",
  "gptprompt", "promptwriter", "chatgptfreelance", "aigeneration", "aicontent", "writergig",
  "blogwriting", "copywriting", "contentwriting", "seowriter", "newsletterjob", "contentcreator",
  "contentfreelance", "contentmanager", "postings", "socialmanager", "smmanager", "smmgig",
  "instagig", "reelsjob", "tiktokjob", "youtubeediting", "videoediting", "reelediting", "capcutgig",
  "adcreation", "posterdesign", "adcampaign", "fbads", "googleads", "marketinggig", "digitalgig",
  "salesfunnel", "emailcampaign", "salespage", "funnelspecialist", "crmsetup", "zapiertask",
  "automationgig", "mailchimp", "aweber", "hubspot", "salesautomation", "crmfreelancer",
  "techfreelancer", "creativefreelancer", "businessfreelancer", "legalfreelancer", "accountinggig",
  "invoicegig", "quickbooksjob", "xerojob", "bookkeepingtask", "budgetgig", "pitchdeck", "deckdesign",
  "presentationjob", "slidesjob", "canvagig", "brandingjob", "logodesign", "logorevision",
  "brandguide", "brandgig", "brandingkit", "freelancebranding", "proposalpdf", "freelancepdf",
  "remoteprofile", "profilelink", "connectnow", "freelancerprofile", "freelancerid",
  "jobfilter", "jobalert", "gighistory", "taskarchive", "pastwork", "completedjob", "reviewme",
  "starfeedback", "toprated", "expertfreelancer", "prolevel", "freelancetier", "levelone",
  "leveltwo", "toprank", "freelancetop", "freelanceking", "gighero", "remotechamp", "hustlegod"],



banking: ["bank", "banking", "finance", "financial", "fintech", "money", "payment", "wallet", "upi",
  "transaction", "transactions", "paymentalert", "moneyalert", "debit", "credit", "credited",
  "debited", "withdraw", "withdrawal", "deposit", "deposited", "balance", "account", "accounts",
  "savings", "current", "checking", "passbook", "statement", "monthlystatement", "bankstatement",
  "cheque", "check", "checkbook", "atm", "atmcard", "card", "creditcard", "debitcard", "virtualcard",
  "mastercard", "visa", "rupay", "maestro", "cardlimit", "cardstatement", "pinupdate", "cardalert",
  "cardtransaction", "otp", "securepin", "securecode", "netbanking", "mobilebanking", "e-banking",
  "digitalbank", "mobilewallet", "netpay", "payonline", "onlinepayment", "upipay", "gpay", "paytm",
  "phonepe", "easypaisa", "jazzcash", "paypal", "skrill", "stripe", "payoneer", "cashapp", "zelle",
  "venmo", "wise", "revolut", "neobank", "onlinebank", "interest", "interestcredit", "interestearned",
  "bankfees", "fees", "charges", "minimumbalance", "bankalert", "smsalert", "emailalert", "funds",
  "fundtransfer", "imps", "neft", "rtgs", "swift", "iban", "bic", "sortcode", "routingnumber",
  "bankcode", "branchcode", "ifsc", "bankname", "accountnumber", "accountinfo", "accdetails",
  "fundrequest", "transferdone", "transferpending", "paymentpending", "invoice", "invoicenumber",
  "invoicepaid", "invoiceunpaid", "billpayment", "bills", "duepayment", "dues", "utilitypayment",
  "autopay", "autodebit", "paymentsetup", "loan", "loans", "loanaccount", "loanstatement", "loanalert",
  "loanemi", "emi", "monthlyemi", "loanbalance", "loanstatus", "homeloan", "personalloan",
  "carloan", "educationloan", "goldloan", "paylater", "bnpl", "creditline", "creditscore",
  "cibil", "creditscorealert", "creditscoreupdate", "creditreport", "equifax", "transunion",
  "experian", "scorecheck", "financialscore", "reportgenerated", "loanapproval", "loanrequest",
  "loanapply", "loanoffer", "loanpreapproved", "preapproved", "eligibleloan", "eligibilitycheck",
  "financeoffer", "financeplan", "investment", "investments", "portfolio", "stock", "stocks",
  "mutualfund", "mutualfunds", "sip", "sipplan", "stockalert", "ipo", "nfo", "dividend", "yield",
  "equity", "debtfund", "balancedfund", "nav", "fundvalue", "fundtracker", "market", "sharemarket",
  "stockmarket", "trading", "demat", "demataccount", "broker", "brokerage", "brokeragefees",
  "brokeraccount", "angelone", "zerodha", "groww", "etmoney", "kuvera", "upstox", "icicidirect",
  "hdfcsecurities", "nse", "bse", "index", "sensex", "nifty", "bull", "bear", "marketnews",
  "marketupdate", "marketwatch", "wealth", "wealthmanager", "wealthplan", "wealthtracker",
  "goaltracker", "savingsgoal", "emergencyfund", "retirementfund", "pension", "pensionfund",
  "pf", "nps", "epf", "ppf", "insurance", "lifeinsurance", "termplan", "mediclaim", "carinsurance",
  "bikeinsurance", "travelinsurance", "policy", "policyalert", "renewalalert", "premium",
  "insurancepremium", "insurancequote", "policybond", "claims", "claimstatus", "claimrequest",
  "claimapproved", "financeplanner", "finadvisor", "advisor", "roboadvisor", "planner",
  "budget", "budgeting", "budgetplanner", "expense", "expensetracker", "moneytracker",
  "dailyexpenses", "billtracker", "billreminder", "duedate", "reminder", "alert", "bankreminder",
  "financialreminder", "investmentplan", "investmenttip", "stocktip", "sipreminder", "monthlysaving",
  "savingplan", "moneygrowth", "earnmoney", "sideincome", "passiveincome", "revenue", "cashflow",
  "inflow", "outflow", "debt", "loanrepay", "repayment", "repayschedule", "loanclosure",
  "bankletter", "kyc", "ekyc", "kycupdated", "kycverified", "ckyc", "panupdate", "aadhaarlink",
  "idverified", "verification", "limitincrease", "creditlimit", "offeravailable", "bankoffer",
  "cashback", "rewardpoints", "pointsbalance", "rewardalert", "redemption", "redeempoints",
  "spendingalert", "spendinglimit", "financeupdates", "mybank", "mywallet", "mymoney",
  "financecenter", "moneycenter", "asset", "assets", "liability", "financialhealth",
  "banklocation", "bankbranch", "atmlocator", "chequestatus", "chequebook", "chequerequest",
  "cashdeposit", "branchvisit", "helpline", "supportteam", "bankofficer", "customercare",
  "supportticket", "bankmessage", "securemail", "encryptedmessage", "safealert",
  "fraudalert", "suspiciousactivity", "unusualspend", "unauthorizedaccess", "blockcard",
  "cardhotlist", "securityupdate", "otpalert", "securepayment", "kyccompliance",
  "rbi", "sebi", "irda", "nbfc", "psubank", "privatebank", "cooperativebank",
  "investmentbank", "corporatebanking", "retailbank", "neobanking", "virtualbank",
  "safevault", "lockerservice", "securevault", "goldlocker", "forex", "currencyexchange",
  "foreigntransfer", "remittance", "wiretransfer", "internationalbank", "currencyalert",
  "fxrates", "bankholiday", "banktiming", "financenews", "tax", "incometax", "taxslab",
  "taxportal", "taxfiling", "itr", "taxreturn", "refundstatus", "taxtoken", "gst",
  "gstinvoice", "gstfiling", "gstportal", "gstalert", "incomedeclaration", "tds",
  "form16", "form26as", "salaryslip", "taxdeducted", "taxdeduction", "claimtax",
  "deduction", "rebate", "section80c", "section10", "taxsaver", "salarycredit",
  "salaryalert", "payroll", "incomereport", "formsubmission", "taxcompliance",
  "incomecertificate", "bankcertificate", "ca", "charteredaccountant", "auditor",
  "auditreport", "financialaudit", "formupload", "documentverified", "selfdeclaration"],




education: ["education", "educational", "academy", "academyupdate", "aadhar", "academiccalendar", "act", "admission", "admitcard", "agrischeme",
  "aicte", "appointment", "applyonline", "assembly", "askmentor", "assignment", "assignmentupload", "attendance",
  "attendanceportal", "award", "backpaper", "batch", "betibachao", "bill", "billstatus", "bijli", "birthcertificate",
  "bisp", "bps", "bookbank", "bonafide", "bonafidecertificate", "booth", "cabinet", "campus", "campusdrive",
  "canal", "career", "careerpath", "census", "certificate", "certificateissue", "challan", "chapter",
  "chapterwise", "chairman", "circular", "citizenportal", "class", "classchat", "classgroup", "classleader",
  "classlink", "classnotice", "classroom", "cleanindia", "cmoffice", "codingcontest", "college", "collegeportal",
  "collegeupdate", "collegenews", "competitiveexam", "complaint", "complaintportal", "complaintstatus",
  "connection", "consumerforum", "consumerid", "convocation", "corecourse", "course", "courses", "covidalert",
  "covidcertificate", "cpga", "css", "curriculum", "cvupload", "dc", "deathcertificate", "debate", "degree",
  "degreeverification", "department", "development", "developmentauthority", "digitalbooks", "digitalclass",
  "digitalindia", "director", "directorate", "discussionboard", "distinction", "division", "documentupload",
  "domicile", "doubtclear", "drivefolder", "drivinglicense", "duedate", "ebook", "eduportal", "eduhub", "education",
  "educationdept", "educationform", "educationformgov", "educationgrant", "educationinfo", "educationloan",
  "educational", "edunews", "eduupdate", "elearning", "electricity", "embassy", "enrollment", "epolice", "evaluation",
  "exam", "examalert", "examcenter", "examdate", "examform", "examhub", "examreport", "examroom", "examroutine",
  "exams", "examupdate", "export", "faculty", "failstatus", "fard", "farmer", "feedback", "feepayment", "feeportal",
  "feeslip", "feereminder", "fellowship", "fileupload", "finalexam", "fir", "form16", "form26as", "formsubmission",
  "formulalist", "gpa", "gasbill", "gitlink", "gov", "govannouncement", "govapp", "govcall", "govcampaign",
  "govdata", "govdegree", "govdirectory", "govdocs", "govdrive", "govemail", "govembassy", "govexam",
  "govfile", "govform", "govfunding", "govhelp", "govinitiative", "govinterview", "govjobs", "govlicense",
  "govmail", "govnotice", "govnotification", "govnotificationpk", "govorder", "govpension", "govpdf",
  "govportal", "govpress", "govrank", "govreport", "govscheme", "govservice", "govsignature", "govsms",
  "govsubsidy", "govsurvey", "govtest", "govtraining", "govupdates", "govverification", "govalert",
  "govalertpk", "governing", "government", "govt", "gpa", "grace", "gracemarks", "grant", "grievance",
  "gsa", "gst", "hallticket", "hackathon", "healthcard", "helpline", "hostel", "ias", "idcard", "identity",
  "import", "incometax", "institute", "internalert", "interviewletter", "invigilator", "irrigation",
  "itreturn", "joiningletter", "jobfair", "jobnotification", "jobsalert", "jee", "kisan", "labmanual",
  "law", "learning", "learningalert", "learninghub", "learningportal", "learningtools", "lecture",
  "lecturelink", "legalnotice", "library", "license", "licenserenewal", "linkedinprofile", "lms",
  "loan", "longanswer", "makeinindia", "marriagecertificate", "marksheet", "materiallink", "matholympiad",
  "mcq", "meritlist", "migration", "mindmap", "ministry", "minister", "mocktest", "modeltest", "mna", "mla",
  "municipal", "municipality", "mutation", "nagarsewa", "naac", "nadra", "nationalid", "nationalportal",
  "ncte", "nrega", "newsletter", "noc", "notebook", "notecopy", "notes", "notice", "objectives", "offlineclass",
  "official", "officialdocs", "officialid", "officialletter", "onlineclass", "onlinecourse", "onlinefir",
  "onlineservice", "ordinance", "pan", "panchayat", "parliament", "passport", "passportapply", "passportstatus",
  "pastpapers", "pcs", "pdfnotes", "peer", "peergroup", "placement", "placementcell", "planning", "pmfund",
  "pmrelief", "pmay", "polling", "population", "portfolio", "ppt", "practicepaper", "pressrelease",
  "pradhanmantri", "previouspapers", "project", "projectfile", "projectshowcase", "projectsubmission",
  "promotion", "prospectus", "propertytax", "public", "publiccourt", "publicnotice", "publicrecord",
  "qna", "questionbank", "ranksheet", "ration", "reappear", "receipt", "recordedclass", "register",
  "registration", "registry", "registryoffice", "reliefprogram", "remedial", "reportcard", "result",
  "resultalert", "resultportal", "resultpublish", "resultupdate", "revaluation", "revision", "revisionnote",
  "rti", "rtiportal", "rural", "salaryslip", "samplepaper", "sarkariservice", "savelife", "savewater",
  "school", "schoolalert", "schoolgov", "schoolnews", "schoolportal", "sciencefair", "section80c",
  "secretariat", "semester", "seniorsupport", "session", "sharedrive", "shikshaabhiyan", "shortanswer",
  "skillsupport", "skillindia", "sliptest", "smartclass", "socialwelfare", "sp", "startupindia",
  "starstudent", "statement", "student", "studentachievement", "studentcard", "studentclub",
  "studentcouncil", "studentdiary", "studentgroup", "studentid", "studentloan", "studentportal",
  "studentprofile", "studymaterial", "studynote", "studynow", "study", "studyforum", "studygroup",
  "studyhacks", "studyplan", "studytracker", "subject", "subjective", "supportdesk", "syllabus",
  "teacher", "teachertraining", "teachers", "telegramgroup", "tehsil", "test", "testlink", "testresult",
  "testseries", "textbook", "timelimit", "timetable", "token", "topper", "topperlist", "trade",
  "trainer", "transferorder", "transcript", "tuition", "unit", "unitwise", "university", "uploadproject",
  "urban", "utility", "utilitybill", "utilityportal", "ugc", "userprofile", "vaccination", "village",
  "visaoffice", "viva", "voter", "voterid", "ward", "waterbill", "webinar", "whatsappgroup", "yojana",
  "zoomclass"],




healthcare: ["doctor", "24x7care", "aerobics", "aging", "allergy", "ambulance", "anesthetist", "anxiety", "appointment", "appointmentportal",
  "arthritis", "asthma", "assistantdoctor", "babycare", "babyvaccine", "bmi", "booster", "bp", "burns", "buyonline",
  "calories", "cancer", "capsule", "cardio", "cardiologist", "caregiver", "cashless", "cataract", "checkup",
  "checkupreminder", "childcare", "childclinic", "childspecialist", "cholera", "cityhospital", "claimform",
  "claimrequest", "claimstatus", "claimportal", "clinic", "clinicmanager", "cold", "consultation", "coverletter",
  "covid", "covidalert", "covidcenter", "covidtest", "ctscan", "cut", "dailyreminder", "dengue", "depression",
  "dermatologist", "diagnosis", "diagnostic", "dietplan", "dietitian", "doctor", "doctors", "doctorslot",
  "doctorvisit", "drops", "drugstore", "ecall", "ecg", "ehr", "elderlysupport", "emergency", "emergencycall",
  "emr", "exercise", "eyeglasses", "eyehospital", "eyetest", "familyclinic", "fatigue", "fever", "fertility",
  "fertilitytest", "fitnesstips", "fitness", "flu", "followup", "freeclinic", "fracture", "generalphysician",
  "geriatric", "greenhospital", "growthchart", "gym", "headache", "health", "healthalert", "healthbenefit",
  "healthcard", "healthcare", "healthinsurance", "healthportal", "healthrecord", "healthreport", "healthsms",
  "healthtips", "healthunit", "healthupdate", "hearingaid", "helpline", "homecare", "homevisit", "hospital",
  "hospitals", "immunization", "injection", "injury", "inpatient", "insomnia", "insured", "insurance",
  "insurancecard", "insuranceportal", "insurancenetwork", "ivdrip", "kidneytest", "labappointment",
  "labreport", "labtest", "labupdate", "lactation", "liverfunction", "malaria", "maternity", "medalert",
  "medcare", "medicines", "mediclaim", "medico", "meditation", "mentalhealth", "mentalwellness", "migraine",
  "misseddose", "mobileclinic", "mothercare", "mri", "nausea", "networkhospital", "newborn", "neurologist",
  "nurse", "nurses", "nutrition", "nutritionchart", "obesity", "ointment", "onlinepharmacy", "opd",
  "orderdrugs", "orthopedic", "outpatient", "pads", "pain", "painkiller", "paramedic", "parenting",
  "pathology", "patient", "patientportal", "periods", "pharmacy", "pillalert", "policy", "policyholder",
  "policyupdate", "postnatal", "posture", "premium", "prescribed", "prescription", "prescriptiondrugs",
  "prescriptionportal", "prescriptionupload", "pediatric", "pediatrician", "pillreminder", "prenatal",
  "radiologist", "radiology", "reception", "receptionist", "referral", "rehabcenter", "reportdownload",
  "reportready", "resultalert", "reimbursement", "rxupload", "samplecollection", "scanreport", "selfcare",
  "seniorcare", "shifahospital", "skincarecenter", "specialist", "staffnurse", "steps", "stress",
  "stressrelief", "stroke", "sugarlevel", "sunshineclinic", "surgeon", "surgery", "syrup", "teleconsult",
  "telehealth", "telemedicine", "testresult", "therapy", "thyroidtest", "tpa", "trainer", "treatment",
  "tumor", "ulcer", "ultrasound", "ultrasoundreport", "urgentcare", "urinetest", "virtualcare", "virtualclinic",
  "vitamins", "vomiting", "vaccine", "vaccinealert", "walker", "wellness", "wellnesscenter", "wheelchair",
  "workout", "wound", "xray", "yoga"],




deals: ["deal", "sale", "deals", "offer", "bestseller","offers", "coupon", "hotprice", "coupons", "promo", "promocode", "voucher", "vouchers",
  "discount", "saveloot", "discounts", "cashback", "savemore", "shopmore", "pricecut", "flashdeal", "todaydeal",
  "todayoffer", "onlinedeal", "hotdeal",  "bargain", "stealprice", "slashedprice", "limitedoffer",
  "buy1get1", "bogo", "percentoff", "offcode", "dealzone", "pricebuster",  "weekenddeal", "exclusiveoffer",
  "festivesale", "midnightsale", "earlybird", "prebookoffer", "walletcash", "storecredit", "topdeal", "topoffers",
  "lootdeal", "freeshipping", "freedelivery", "dealday", "shoppingfest", "superdiscount", "pricehack", "bundleoffer",
  "buyget", "redeemcode", "couponalert", "freestuff", "giftvoucher", "limitedstock", "outletdeal", "savebig",
  "blowoutsale", "extraoff", "cheaprate", "dealhunters", "couponzone", "quickdeal", "lowprice", "dealgrabber",
  "clearancesale", "superdeal", "offerzone", "dealoftheday", "checkoutcode", "getreward", "dailyoffer",
  "oneclickdeal", "promopass", "savealert", "cashdeal", "dealbazaar", "dhamakadeal", "bestbuy", "redeemnow",
  "onlinesale", "megasale", "festivedeal", "pricedeal", "topcoupon", "secretdeal", "scratchdeal", "couponbox",
  "rewardwallet", "onlinecoupon", "giftcode", "unlockdeal", "limitedtime", "dealstack", "promoalert", "specialvoucher",
  "smartshopper", "finalprice", "crazydeal", "rushdeal", "holidayoffer", "ecomdeal", "snagdeal", "couponbook",
  "dealhunt", "stealdeal", "stockclear", "supercash", "rewardcash", "unbeatabledeal", "lowestrate", "amazingdeal",
  "bigdiscount", "giftalert", "voucherbank", "cashreward", "savingking", "checkoutoffer", "quickbuy", "dealmatch",
  "epicdeal", "freedeal", "stealalert", "redeemalert", "priceflash", "blitzdeal", "bestoffer", "extracashback",
  "flatdiscount", "walletbonus", "discountmania", "offerhunter", "sneakdeal", "unlockreward", "quicksteal",
  "cashdrop", "extrareward", "freeswag", "fastdeal", "lootoffer", "couponhunt", "dealdrip", "seasonalsale",
  "instantcode", "grabreward", "dealstorm", "flashalert", "hotdiscount", "instantdeal", "openoffer", "grabnow",
  "lightningdeal", "middeal", "grabfast", "freestuffalert", "midmonthdeal", "extraoffer", "instantreward",
  "nextdeal", "easycoupon", "clicksave", "priceloot", "festivebonus", "wishlistdeal", "grabbonus", "checkincode",
  "salehunt", "megaoffer", "primeoffer", "rushhourdeal", "weeklydeals", "savetime", "bestdiscount"],

  
};


